USE axolartl;
ALTER TABLE locations ADD COLUMN image_url VARCHAR(3000) DEFAULT NULL;
ALTER TABLE locations ADD COLUMN image_updated_at TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE locations MODIFY COLUMN image_url VARCHAR(3000) DEFAULT NULL;